import { useState } from "react";
const CodeToggle = ({ label, children }: { label: string; children: React.ReactNode }) => {
  const [open, setOpen] = useState(false);
  return (<div className="my-4"><button onClick={() => setOpen(!open)} className="code-toggle-btn">{open ? "▾" : "▸"} {label}</button>{open && <div className="mt-2">{children}</div>}</div>);
};

export default function Ch7Context() { return (<article className="prose-body">
  <div className="chapter-badge">Chapter 07</div>
  <h1 className="heading-display text-4xl mb-3">Context Engineering</h1>
  <p className="text-lg mb-10" style={{ color: "var(--text-tertiary)", fontFamily: "var(--font-body)" }}>Managing the finite context window — budgets, input construction, and history compaction — is the difference between an agent that works on toy examples and one that works on real families.</p>

  <h2 className="heading-section text-2xl mt-12 mb-6">The Constraint</h2>
  <p>Every LLM call operates within a finite context window. Claude's window is 200k tokens; GPT-4 Turbo's is 128k. This window must contain everything the model needs to produce its output: the system prompt that defines the agent's behavior, the complete conversation history (every prior tool call and its result, accumulated across iterations), the input data (the family_file contents, in whatever form you've injected them), all tool definitions (the JSON schemas that tell the model what tools are available and how to call them), and enough room for the model's output. If the total exceeds the window, the API call fails. If it's close to the limit, the model's performance degrades — it struggles to attend to information at the boundaries of the window.</p>
  <p>For Architecture_V1, context pressure comes from two distinct directions, and they compound in the worst case. First, <strong>within an agent loop</strong>: each tool-use iteration appends to the message history. When the agent calls a web search tool, the result might be 1-5k tokens of scraped web content. When it calls a <code className="code-inline">read_family_file</code> tool, the result is the full JSON serialization of the file. After 5 iterations with 2 tool calls each, the accumulated history can be 10-30k tokens — a significant fraction of the window, and it grows linearly with each iteration. Second, <strong>family_file size as input</strong>: injecting a large family's data into the initial prompt can consume 10-20k tokens for an 8+ member family with rich personal_data. When both factors combine (large family + many iterations), you can burn through 50-80k tokens of context before the agent even begins its final reasoning pass.</p>
  <p>Context engineering is the discipline of fitting all of this into the window, deciding what to include and what to leave out, and ensuring that what you include is structured for maximum model comprehension. It is not an optimization afterthought — it is a first-class design concern that shapes the agent architecture itself.</p>

  <div className="stat-row">
    <div className="stat-card"><div className="stat-card-value">200k</div><div className="stat-card-label">Claude window</div></div>
    <div className="stat-card"><div className="stat-card-value">~3k</div><div className="stat-card-label">System prompt</div></div>
    <div className="stat-card"><div className="stat-card-value">~5k</div><div className="stat-card-label">Per iteration</div></div>
    <div className="stat-card"><div className="stat-card-value">~15k</div><div className="stat-card-label">Large family input</div></div>
  </div>

  <h2 className="heading-section text-2xl mt-12 mb-6">Token Budget Allocation</h2>
  <p>Before constructing any prompt, plan the context window budget. Think of it like a financial budget: you allocate fixed costs (system prompt, tool schemas, output reservation, safety margin), and whatever remains is the variable budget for conversation history. If the fixed costs exceed the window, you have a structural problem. If the variable budget is too small for the expected iteration count, the agent will run out of context mid-execution.</p>
  <p>The budget breaks down as follows. The <strong>system prompt</strong> is typically 1-3k tokens — it's a fixed cost that doesn't grow with the data. The <strong>tool schemas</strong> cost 50-200 tokens per tool, depending on the complexity of the parameter descriptions; an agent with 5 tools might consume 500-1000 tokens just for the schemas. The <strong>output reservation</strong> is the <code className="code-inline">max_tokens</code> setting you pass to the API — the maximum tokens the model is allowed to generate in its response. The <strong>safety margin</strong> accounts for tokenizer estimation errors (your character-based approximation of token count won't be exact) and for the overhead of message framing (role labels, content type markers). A 5k token safety margin is conservative but safe.</p>
  <p>What remains after subtracting all fixed allocations is the <strong>history budget</strong> — the pool of tokens available for the user messages and assistant messages that accumulate during the agent loop. Dividing this by the estimated tokens per iteration gives you the maximum number of iterations the agent can run before context exhaustion. If your history budget is 50k tokens and each iteration consumes about 5k tokens (a web search result + the model's tool call + the next prompt), the agent can iterate roughly 10 times. Plan accordingly.</p>

  <div className="callout">
    <strong>Budget Audit</strong>
    <p className="mt-2 mb-0">The budget audit should run <em>before every agent invocation</em>. If the input data alone would consume 80% of the available budget, the context strategy must switch (from full injection to summary-plus-detail-on-demand, or from whole-family mode to per-member mode). Discovering mid-execution that you've run out of context is expensive — you've already spent the tokens for the iterations that completed before the failure, and you have no way to recover the model's intermediate reasoning.</p>
  </div>

  <h2 className="heading-section text-2xl mt-12 mb-6">Input Construction Strategies</h2>
  <p>The input is the data you give the agent to work with. For Architecture_V1, this is primarily the family_file (or relevant subsets of it). Three strategies exist, in order of increasing sophistication and token efficiency.</p>

  <h3 className="heading-sub text-xl mt-8 mb-4">Strategy 1: Full Context Injection</h3>
  <p>Pass the entire family_file as part of the user message — serialize it to JSON and include it verbatim. This is the simplest approach and the most intuitive: the model sees everything, so it can reason about the complete family state. A 5-member family with moderate data consumes 3-5k tokens. A 10-member family with rich personal_data can be 15-20k tokens. Use this for small families in whole-family mode, or on first passes where the data is sparse and the file is small.</p>
  <p>The downside is that the model may not need most of the data. A career enrichment agent receiving a full family_file with 8 members' social media links, education histories, and relationship data is getting far more context than it needs to look up someone's job title. The model still processes all of it, paying an attention cost and an inference latency cost for information it will never use.</p>

  <h3 className="heading-sub text-xl mt-8 mb-4">Strategy 2: Summary Plus Detail-on-Demand</h3>
  <p>Inject a compact summary into the prompt — member names, relationships, and field fill rates — and provide a <code className="code-inline">read_member_data</code> tool that retrieves full details for specific members. The summary is 200-500 tokens regardless of family size. The agent reads the summary, identifies which members it needs to examine in detail, and fetches only those members' data via tool calls. Tokens are consumed incrementally, on demand, rather than upfront for the entire family.</p>
  <p>This is the preferred strategy for large families and per-member mode agents. The tradeoff is latency: each detail fetch is an additional tool-use iteration, adding one round trip to the LLM. For an agent that needs to examine 3 out of 10 members, the net effect is positive — you save the 7 members' worth of upfront tokens and spend only 3 tool-call iterations. For an agent that needs to examine all 10 members, you've made things slower without saving tokens. The policy's config builder should choose the strategy based on the expected usage pattern.</p>

  <h3 className="heading-sub text-xl mt-8 mb-4">Strategy 3: Targeted Projection</h3>
  <p>Inject only the fields relevant to the agent's task. A career enrichment agent doesn't need social media links or early life data. The projection filters the family_file to include only the field categories specified in the agent config. This produces the smallest possible input — sometimes as little as 500 tokens for a single member's relevant fields — and the most focused prompt. The model doesn't waste attention on irrelevant data, which empirically improves output quality for targeted tasks.</p>
  <p>The tradeoff is coupling: the config builder must know which fields each agent cares about. If you add a new agent that uses a novel combination of fields, you need to update the projection mapping. This is manageable for the MVP (static agent registry → static field mappings) but becomes cumbersome as the agent registry grows. The skill system (Chapter 8) can eventually learn optimal projections from telemetry data.</p>

  <div className="section-divider">History Management</div>

  <h2 className="heading-section text-2xl mt-12 mb-6">Conversation History Compaction</h2>
  <p>As the agent loop iterates, the conversation history grows. At some point — often around iteration 6-8 for a typical agent — the accumulated history threatens to exceed the available budget. Three strategies handle this, in order of complexity and information preservation. In practice, you should implement all three and apply them in sequence: truncate first (cheapest), then slide if needed, then summarize as a last resort.</p>

  <h3 className="heading-sub text-xl mt-8 mb-4">Truncate Tool Results at Return Time</h3>
  <p>Before appending a tool result to the history, truncate it to a maximum token count — say, 2000 tokens. Keep the first portion and the last portion (head and tail), with a truncation notice in between. This is the cheapest approach: no extra LLM calls, no information loss for short results, and predictable history growth. The truncation threshold should be tuned per tool type — web search results can usually be truncated aggressively (the first few snippets contain the most relevant information), while family_file reads should be truncated more conservatively (the structure matters, and truncating mid-JSON can confuse the model).</p>

  <h3 className="heading-sub text-xl mt-8 mb-4">Sliding Window with Key Fact Extraction</h3>
  <p>Keep only the last N exchanges in full. For discarded exchanges, extract key facts using pattern matching (not LLM calls) on tool names and results. For example: "Searched for 'Robert Chen CEO' → found LinkedIn profile at Goldman Sachs." The extracted facts are prepended to the history as a compact summary message. This preserves the most important information from older exchanges while bounding total history size. The extraction is deterministic and fast — regex patterns on tool names and result structures, not semantic analysis.</p>

  <h3 className="heading-sub text-xl mt-8 mb-4">Summarize Old Exchanges</h3>
  <p>When the history exceeds a threshold and the sliding window isn't sufficient, summarize all but the most recent 2 exchanges using a cheap, fast model (Claude Haiku). The summary captures what was searched, what was found, and what actions were taken. The entire old history is replaced with a single message containing the summary. This is the most expensive approach — an extra LLM call that adds latency and cost — but it preserves the most information per token. Use it as a last resort, not as a default.</p>

  <h2 className="heading-section text-2xl mt-12 mb-6">Model Selection by Context Needs</h2>
  <p>Different agents have different context requirements, and models have different context window sizes, capabilities, and costs. Matching the model to the agent's needs is a cost-optimization decision that the policy's config builder makes.</p>
  <p>Cold-start discovery uses a small context (just a name and class year) and doesn't need deep reasoning — a fast, cheap model like Claude Haiku is ideal, handling the task in under a second at minimal cost. Per-member enrichment needs medium context and moderate reasoning — Claude Sonnet balances capability and cost. Whole-family enrichment needs the full context window and strong reasoning about inter-member relationships — Sonnet or Opus depending on the family's complexity. Cross-reference discovery injects population context from the population index, requiring a large context window and strong analytical capability — this is where Opus earns its cost premium.</p>
  <p>The model is specified in the AgentConfig, which means it can vary not just by agent type but by retry attempt. A cold start that fails with Haiku might be retried with Sonnet — the config builder upgrades the model for the retry, spending more tokens on a problem that the cheaper model couldn't solve. This adaptive model selection is a simple but effective optimization that the static agent selector can implement with just an additional branch based on the retry count.</p>
</article>); }
